export const vendorLedgerColumns = [
    {
        header: "Bill No.",
        accessor: "billNo",
    },
    {
        header: "Against PO",
        accessor: "againstPO",
    },
    {
        header: "Bill Date",
        accessor: "billDate",
    },
    {
        header: "Due Date",
        accessor: "dueDate",
    },
    {
        header: "Bill Amount(SAR)",
        accessor: "billAmount",
    },
    {
        header: "Paid Amount (SAR)",
        accessor: "paidAmount",
    },
    {
        header: "Balance Due",
        accessor: "balanceDue",
    },
    {
        header: "Status",
        accessor: "status",
    },
    {
        header: "Action",
        accessor: "action",
    },
];

export const vendorLedgerData = [
    {
        id: 1,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "4,511.00",
        paidAmount: "4,511.00",
        balanceDue: "0.00",
        status: "Paid",
        showEdit: false,
        showDelete: false,
    },
    {
        id: 2,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "9,904.20",
        paidAmount: "5,000.00",
        balanceDue: "4,904.20",
        status: "Partially Paid",
        showEdit: true,
        showDelete: false,
    },
    {
        id: 3,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "6,412.55",
        paidAmount: "0.00",
        balanceDue: "6,412.55",
        status: "Unpaid",
        showEdit: true,
        showDelete: true,
    },
    {
        id: 4,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "3,275.00",
        paidAmount: "0.00",
        balanceDue: "3,275.00",
        status: "Overdue",
        showEdit: true,
        showDelete: false,
    },
    {
        id: 5,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "8,940.00",
        paidAmount: "3,000.00",
        balanceDue: "5,940.00",
        status: "Overdue",
        showEdit: false,
        showDelete: false,
    },
    {
        id: 6,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "2,088.00",
        paidAmount: "1,000.00",
        balanceDue: "1,088.00",
        status: "Overdue",
        showEdit: false,
        showDelete: false,
    },
    {
        id: 7,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "5,150.00",
        paidAmount: "5,150.00",
        balanceDue: "0.00",
        status: "Paid",
        showEdit: true,
        showDelete: true,
    },
    {
        id: 8,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "7,250.00",
        paidAmount: "7,250.00",
        balanceDue: "0.00",
        status: "Paid",
        showEdit: false,
        showDelete: false,
    },
    {
        id: 9,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "12,450.00",
        paidAmount: "8,000.00",
        balanceDue: "4,450.00",
        status: "Partially Paid",
        showEdit: true,
        showDelete: false,
    },
    {
        id: 10,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "4,680.00",
        paidAmount: "0.00",
        balanceDue: "4,680.00",
        status: "Unpaid",
        showEdit: true,
        showDelete: true,
    },
    {
        id: 11,
        billNo: "SO 0123",
        againstPO: "April 28, 2026",
        billDate: "April 28, 2026",
        dueDate: "April 28, 2026",
        billAmount: "6,300.00",
        paidAmount: "0.00",
        balanceDue: "6,300.00",
        status: "Overdue",
        showEdit: true,
        showDelete: false,
    },
];