export const debitNoteColumns = [
  {
    header: "Debit Note No.",
    accessor: "debitNoteNo",
  },
  {
    header: "Against Bill",
    accessor: "againstBill",
  },
  {
    header: "Date Issued",
    accessor: "dateIssued",
  },
  {
    header: "Reason",
    accessor: "reason",
  },
  {
    header: "Bill Amt (SAR)",
    accessor: "billAmount",
  },
  {
    header: "Debit Amt (SAR)",
    accessor: "debitAmount",
  },
  {
    header: "After Applied (SAR)",
    accessor: "afterApplied",
  },
  {
    header: "Status",
    accessor: "status",
  },
  {
    header: "Action",
    accessor: "action",
  },
];

export const debitNoteData = [
  {
    id: 1,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Damaged Goods",
    billAmount: "8,940.00",
    debitAmount: "3,000.00",
    afterApplied: "5,940.00",
    status: "Issued",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 2,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Short Delivery",
    billAmount: "4,511.00",
    debitAmount: "1,210.00",
    afterApplied: "3,301.00",
    status: "Issued",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 3,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Purchase Return",
    billAmount: "9,904.20",
    debitAmount: "730.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 4,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Billing Error",
    billAmount: "2,088.00",
    debitAmount: "500.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 5,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Damaged Goods",
    billAmount: "5,150.00",
    debitAmount: "250.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 6,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Short Delivery",
    billAmount: "6,820.00",
    debitAmount: "160.00",
    afterApplied: "-",
    status: "Cancelled",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 7,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Damaged Goods",
    billAmount: "1,850.00",
    debitAmount: "90.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 8,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Billing Error",
    billAmount: "4,250.00",
    debitAmount: "270.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
  {
    id: 9,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Purchase Return",
    billAmount: "3,200.00",
    debitAmount: "400.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
  {
    id: 10,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Damaged Goods",
    billAmount: "4,000.00",
    debitAmount: "300.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
  {
    id: 11,
    debitNoteNo: "VPAY0211",
    againstBill: "BILL 0398",
    dateIssued: "April 28, 2026",
    reason: "Short Delivery",
    billAmount: "5,600.00",
    debitAmount: "350.00",
    afterApplied: "-",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
];