// Temporary data until the purchase order API exists.
// Field names mimic what a Django serializer would likely return.
// Delete this file once the slice + service are wired up.

export const purchaseOrderData = [
    {
        id: 1,
        po_number: "PO-0001",
        vendor_id: "1",
        vendor_name: "ABC Trading LLC",
        order_date: "2026-09-01",
        expected_delivery_date: "2026-09-15",
        payment_term_name: "30 Days",
        order_status: "pending",
        currency: "SAR",
        total_amount: 12500,
    },
    {
        id: 2,
        po_number: "PO-0002",
        vendor_id: "2",
        vendor_name: "XYZ Supplies",
        order_date: "2026-09-03",
        expected_delivery_date: "2026-09-20",
        payment_term_name: "15 Days",
        order_status: "approved",
        currency: "SAR",
        total_amount: 8400.5,
    },
    {
        id: 3,
        po_number: "PO-0003",
        vendor_id: "3",
        vendor_name: "Global Suppliers",
        order_date: "2026-09-05",
        expected_delivery_date: "2026-09-25",
        payment_term_name: "Due on Receipt",
        order_status: "partially_received",
        currency: "SAR",
        total_amount: 23150,
    },
    {
        id: 4,
        po_number: "PO-0004",
        vendor_id: "4",
        vendor_name: "Al Noor Trading",
        order_date: "2026-09-08",
        expected_delivery_date: "2026-09-30",
        payment_term_name: "60 Days",
        order_status: "draft",
        currency: "SAR",
        total_amount: 4990,
    },
    {
        id: 5,
        po_number: "PO-0005",
        vendor_id: "1",
        vendor_name: "ABC Trading LLC",
        order_date: "2026-09-10",
        expected_delivery_date: "2026-10-02",
        payment_term_name: "45 Days",
        order_status: "received",
        currency: "SAR",
        total_amount: 17800,
    },
    {
        id: 6,
        po_number: "PO-0006",
        vendor_id: "2",
        vendor_name: "XYZ Supplies",
        order_date: "2026-09-12",
        expected_delivery_date: "2026-10-05",
        payment_term_name: "7 Days",
        order_status: "cancelled",
        currency: "SAR",
        total_amount: 3200,
    },
];