import { FaEdit, FaTrash } from "react-icons/fa";

export const employeeColumns = [
  {
    header: "Sl No",
    accessor: "id",
  },
  {
    header: "Employee Name",
    accessor: "name",
  },
  {
    header: "Username",
    accessor: "username",
  },
  {
    header: "Phone Number",
    accessor: "phone",
  },
  {
    header: "Employee ID",
    accessor: "employeeId",
  },
  {
    header: "Designation",
    accessor: "designation",
  },
  {
    header: "Department",
    accessor: "department",
  },
  {
    header: "Status",
    accessor: "status",
  },
  {
    header: "Action",
    accessor: "action",
    sortable: false,
  },
];

export const employeeData = [
  {
    id: 1,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9876543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 2,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9876543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 3,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 4,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 5,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 6,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 7,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 8,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 9,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 10,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
    {
    id: 11,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 12,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 13,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 14,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 15,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 16,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 17,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 18,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 19,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 20,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 21,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 22,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 23,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 24,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 25,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 26,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 27,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 28,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 29,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 30,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 31,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 32,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 33,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 34,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 35,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 36,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 37,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 38,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 39,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 40,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 41,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 42,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 43,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 44,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 45,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 46,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 47,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 48,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 49,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 50,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 51,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 52,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 53,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 54,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 55,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 56,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
  {
    id: 57,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 59,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
   {
    id: 60,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },

  {
    id: 61,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9876543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 62,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9876543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 63,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 64,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 65,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 66,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 67,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 68,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 69,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 70,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 71,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9876543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 72,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9876543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 73,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 74,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 75,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 76,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 77,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 78,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 79,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 80,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9886543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 81,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9886543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 82,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9886543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 83,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9886543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 84,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9886543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 85,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9886543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 86,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9886543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 87,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 88,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9886543218",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 89,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 90,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9996543219",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 91,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9996543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 92,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9996543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 93,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9996543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 94,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9996543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 95,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9996543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 96,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9996543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 97,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9976543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 98,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9996543219",
    employeeId: "EMP009",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 99,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9976543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 100,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9996543219",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
   {
    id: 101,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9886543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 102,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9886543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 103,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9886543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 104,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9886543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 105,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9886543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 106,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9886543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 107,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 108,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9886543218",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 109,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },

];

export const reimbursementColumns = [
    {
        header: "Employee",
        accessor: "employeeName",
    },
    {
        header: "Reimbursement Type",
        accessor: "reimbursementType",
    },
    {
        header: "Amount",
        accessor: "amount",
    },
    {
        header: "Date",
        accessor: "date",
    },
    {
        header: "Description",
        accessor: "description",
    },
    {
        header: "Status",
        accessor: "status",
    },
];
export const reimbursementData = [
    {
        id: 1,
        employeeName: "Ansal",
        reimbursementType: "Travel",
        amount: "₹12,500",
        date: "21-08-2026",
        description: "Client meeting travel expenses",
        status: "Approved",
    },
    {
        id: 2,
        employeeName: "Rahul",
        reimbursementType: "Medical",
        amount: "₹8,500",
        date: "20-08-2026",
        description: "Medical expenses",
        status: "Pending",
    },
    {
        id: 3,
        employeeName: "Priya",
        reimbursementType: "Food",
        amount: "₹4,500",
        date: "19-08-2026",
        description: "Business lunch expenses",
        status: "Approved",
    },
    {
        id: 4,
        employeeName: "Amit",
        reimbursementType: "Fuel",
        amount: "₹6,000",
        date: "18-08-2026",
        description: "Official travel fuel expenses",
        status: "Rejected",
    },
    {
        id: 5,
        employeeName: "Rishal",
        reimbursementType: "Accommodation",
        amount: "₹15,000",
        date: "17-08-2026",
        description: "Business trip accommodation",
        status: "Pending",
    },
];