const num = (v) => (v === "" || v == null ? undefined : Number(v));
const str = (v) => (v === "" || v == null ? undefined : v);

// Modal form data -> API payload, using the Django Vendor model field names.
// vendor_id is generated by the backend, so it is never sent.
// Documents are uploaded separately (VendorDocument).
export const buildVendorPayload = (f) => {
  const billingAddress = (f.billingAddresses || [])
    .map((a) => a.trim())
    .filter(Boolean)
    .join("\n"); // model has a single TextField, so join multiple addresses

  const payload = {
    name: f.vendorName,
    vendor_type: str(f.vendorType),
    opening_balance: num(f.openingBalance),
    credit_limit: num(f.creditLimit),
    cr_number: str(f.crNumber),
    currency: str(f.currency),
    vat_registration_number: str(f.vatNumber),
    payment_term: str(f.paymentTerm),
    cr_expiry_date: str(f.crExpiryDate),
    billing_address: str(billingAddress),
    city: str(f.city),
    state: str(f.state),
    country: str(f.country),
    postal: str(f.postalCode),
    phno: str(f.phoneNumber),
    admin_email: str(f.adminEmail),
    financial_email: str(f.financialEmail),
    technical_email: str(f.technicalEmail),
    client_status: f.clientStatus ? f.clientStatus.toLowerCase() : undefined,
    bank_name: str(f.bankName),
    account_num: str(f.accountNumber),
    iban: str(f.ibanNumber),
    branch: str(f.branch),
  };

  // drop undefined keys so model defaults apply
  return Object.fromEntries(
    Object.entries(payload).filter(([, v]) => v !== undefined)
  );
};

// Turns a DRF error ({ field: ["msg"] } | { detail } | string) into text
export const formatApiError = (error) => {
  if (!error) return "";
  if (typeof error === "string") return error;
  if (error.detail) return error.detail;

  return Object.entries(error)
    .map(([field, msg]) =>
      `${field}: ${Array.isArray(msg) ? msg.join(", ") : msg}`
    )
    .join(" | ");
};

export const vendorToForm = (v = {}) => {
  const status = v.client_status || "";
  return {
    vendorId: v.vendor_id ?? "",
    vendorName: v.name ?? "",
    vendorType: v.vendor_type ?? "",
    openingBalance: v.opening_balance ?? "",
    creditLimit: v.credit_limit ?? "",
    crNumber: v.cr_number ?? "",
    currency: v.currency || "SAR",
    vatNumber: v.vat_registration_number ?? "",
    paymentTerm: v.payment_term ?? "",
    crExpiryDate: v.cr_expiry_date ?? "",
    city: v.city ?? "",
    state: v.state ?? "",
    country: v.country ?? "",
    postalCode: v.postal ?? "",
    phoneNumber: v.phno ?? "",
    adminEmail: v.admin_email ?? "",
    financialEmail: v.financial_email ?? "",
    technicalEmail: v.technical_email ?? "",
    clientStatus: status ? status.charAt(0).toUpperCase() + status.slice(1) : "",
    bankName: v.bank_name ?? "",
    accountNumber: v.account_num ?? "",
    ibanNumber: v.iban ?? "",
    branch: v.branch ?? "",
    documents: null,
  };
};

export const vendorAddresses = (v = {}) => {
  const list = (v.billing_address || "").split("\n").map((a) => a.trim()).filter(Boolean);
  return list.length ? list : [""];
};