export const paymentColumns = [
  {
    header: "Payment No.",
    accessor: "paymentNo",
  },
  {
    header: "Against Bill",
    accessor: "againstBill",
  },
  {
    header: "Payment Date",
    accessor: "paymentDate",
  },
  {
    header: "Method",
    accessor: "method",
  },
  {
    header: "Reference No.",
    accessor: "referenceNo",
  },
  {
    header: "Amount (SAR)",
    accessor: "amount",
  },
  {
    header: "Status",
    accessor: "status",
  },
  {
    header: "Action",
    accessor: "action",
  },
];

export const paymentData = [
  {
    id: 1,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "4,511.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 2,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "5,000.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 3,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Online Payment",
    referenceNo: "TXN-88401",
    amount: "3,000.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 4,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Cheque",
    referenceNo: "TXN-88401",
    amount: "1,000.00",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
  {
    id: 5,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "5,150.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 6,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "6,820.00",
    status: "Failed",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 7,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Cash",
    referenceNo: "-",
    amount: "1,850.00",
    status: "Pending",
    showEdit: true,
    showDelete: true,
  },
  {
    id: 8,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "4,250.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 9,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Online Payment",
    referenceNo: "TXN-88401",
    amount: "2,500.00",
    status: "Cleared",
    showEdit: false,
    showDelete: false,
  },
  {
    id: 10,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Cheque",
    referenceNo: "TXN-88401",
    amount: "3,200.00",
    status: "Pending",
    showEdit: true,
    showDelete: false,
  },
  {
    id: 11,
    paymentNo: "VPAY0211",
    againstBill: "BILL 0398",
    paymentDate: "April 28, 2026",
    method: "Bank Transfer",
    referenceNo: "TXN-88401",
    amount: "4,000.00",
    status: "Failed",
    showEdit: false,
    showDelete: false,
  },
];