export const vendorLedgerColumns = [
    {
        header: "Date",
        accessor: "date",
    },
    {
        header: "Reference",
        accessor: "reference",
    },
    {
        header: "Description",
        accessor: "description",
    },
    {
        header: "Debit",
        accessor: "debit",
    },
    {
        header: "Credit",
        accessor: "credit",
    },
    {
        header: "Balance",
        accessor: "balance",
    },
];

export const vendorLedgerData = [
    {
        id: 1,
        date: "2026-09-01",
        reference: "PO-001",
        description: "Purchase Order",
        debit: 5000,
        credit: 0,
        balance: 5000,
    },
    {
        id: 2,
        date: "2026-09-03",
        reference: "PAY-001",
        description: "Payment to Vendor",
        debit: 0,
        credit: 2000,
        balance: 3000,
    },
    {
        id: 3,
        date: "2026-09-05",
        reference: "PO-002",
        description: "Purchase Order",
        debit: 7500,
        credit: 0,
        balance: 10500,
    },
    {
        id: 4,
        date: "2026-09-08",
        reference: "PAY-002",
        description: "Payment to Vendor",
        debit: 0,
        credit: 3500,
        balance: 7000,
    },
    {
        id: 5,
        date: "2026-09-10",
        reference: "PO-003",
        description: "Purchase Order",
        debit: 4200,
        credit: 0,
        balance: 11200,
    },
    {
        id: 6,
        date: "2026-09-12",
        reference: "CN-001",
        description: "Credit Note",
        debit: 0,
        credit: 1200,
        balance: 10000,
    },
    {
        id: 7,
        date: "2026-09-15",
        reference: "PO-004",
        description: "Purchase Order",
        debit: 6800,
        credit: 0,
        balance: 16800,
    },
    {
        id: 8,
        date: "2026-09-18",
        reference: "PAY-003",
        description: "Payment to Vendor",
        debit: 0,
        credit: 5000,
        balance: 11800,
    },
    {
        id: 9,
        date: "2026-09-20",
        reference: "PO-005",
        description: "Purchase Order",
        debit: 3500,
        credit: 0,
        balance: 15300,
    },
    {
        id: 10,
        date: "2026-09-22",
        reference: "PAY-004",
        description: "Payment to Vendor",
        debit: 0,
        credit: 3000,
        balance: 12300,
    },
    {
        id: 11,
        date: "2026-09-24",
        reference: "PO-006",
        description: "Purchase Order",
        debit: 9000,
        credit: 0,
        balance: 21300,
    },
    {
        id: 12,
        date: "2026-09-26",
        reference: "PAY-005",
        description: "Payment to Vendor",
        debit: 0,
        credit: 4500,
        balance: 16800,
    },
];