import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate, useParams } from "react-router-dom";

// Match the file name/casing you actually have for the slice
import {
  addPurchaseOrder,
  editPurchaseOrder,
  getPurchaseOrderById,
  getVendorOptions,
  getWarehouseOptions,
  getProductOptions,
  clearPurchaseOrderError,
} from "../../../../../Redux/finance/purchases/Purchaseordersslice";
import { getVendors } from "../../../../../Redux/finance/purchases/vendorsSlice";

// ---- Dropdown options that are fixed values ----

// The API example sends "30 days". Confirm which exact strings the backend accepts.
export const PAYMENT_TERMS = [
  { value: "Due on receipt", label: "Due on Receipt" },
  { value: "7 days", label: "7 Days" },
  { value: "15 days", label: "15 Days" },
  { value: "30 days", label: "30 Days" },
  { value: "45 days", label: "45 Days" },
  { value: "60 days", label: "60 Days" },
  { value: "90 days", label: "90 Days" },
];

export const ORDER_STATUSES = [
  { value: "draft", label: "Draft" },
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "ordered", label: "Ordered" },
  { value: "partially_received", label: "Partially Received" },
  { value: "received", label: "Received" },
  { value: "cancelled", label: "Cancelled" },
];

export const SHIPPING_METHODS = [
  { value: "road", label: "Road" },
  { value: "air", label: "Air" },
  { value: "sea", label: "Sea" },
  { value: "courier", label: "Courier" },
  { value: "pickup", label: "Pickup" },
  { value: "other", label: "Other" },
];

const VAT_RATE = 15;

// Must start with "/" and match the route your list page is registered on
const LIST_ROUTE = "/purchase/purchaseorder";

// ---- Helpers ----

let nextItemId = 1;
const newItem = (slNo = 1) => ({
  id: nextItemId++,
  slNo,
  product: "",
  description: "",
  qty: "",
  hsCode: "",
  rate: "",
  vat: String(VAT_RATE),
});

const toNum = (v) => {
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : 0;
};

// "100.00" -> "100" for editable inputs; null -> ""
const numStr = (v) => (v == null || v === "" ? "" : String(parseFloat(v)));

const money = (n) => Number(n || 0).toFixed(2);

// Per-row maths, kept in one place so the table and summary always agree.
// Matches the backend: amount = qty * rate + VAT.
const rowTotals = (row) => {
  const base = toNum(row.qty) * toNum(row.rate);
  const vatAmount = (base * toNum(row.vat)) / 100;
  return { base, vatAmount, amount: base + vatAmount };
};

const fmt = (n) =>
  n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

// Turns a DRF error ({ field: ["msg"] } | { detail } | string) into text
const formatError = (error) => {
  if (!error) return "";
  if (typeof error === "string") return error;
  if (error.detail) return error.detail;
  return Object.entries(error)
    .map(([field, msg]) => `${field}: ${Array.isArray(msg) ? msg.join(", ") : msg}`)
    .join(" | ");
};

const useAddingPurchaseOrder = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();

  // An :id in the URL means edit mode, otherwise add
  const { id } = useParams();
  const isEdit = Boolean(id);
  const [isLoading, setIsLoading] = useState(isEdit);

  const {
    vendorOptions: rawVendors = [],
    warehouseOptions: rawWarehouses = [],
    productOptions: rawProducts = [],
  } = useSelector((state) => state.purchaseOrder) || {};

  // Vendors from the Vendors module, used when the PO dropdown returns nothing
  const moduleVendors = useSelector((state) => state.vendor?.vendors) || [];
  const sourceVendors = rawVendors.length ? rawVendors : moduleVendors;

  const [form, setForm] = useState({
    vendorId: "",
    poNumber: "", // generated by the backend, display only
    prReference: "",
    orderDate: new Date().toISOString().slice(0, 10),
    expectedDate: "",
    paymentTerm: "",
    orderStatus: "draft",
    warehouse: "",
    shippingMethod: "",
    discount: "",
    roundOff: "",
    notes: "", // kept so editing doesn't wipe existing notes
  });
  const [items, setItems] = useState([newItem(1)]);
  const [errors, setErrors] = useState({});
  const [saveError, setSaveError] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // ---- Dropdown data ----

  useEffect(() => {
    dispatch(clearPurchaseOrderError());
    dispatch(getVendorOptions());
    dispatch(getWarehouseOptions());
    dispatch(getProductOptions());
    dispatch(getVendors({ page: 1, page_size: 100, ordering: "name" }));
  }, [dispatch]);

  const vendorOptions = useMemo(
    () =>
      sourceVendors.map((v) => ({
        value: String(v.id ?? v.value),
        label: v.name || v.vendor_name || v.label || `Vendor #${v.id}`,
      })),
    [sourceVendors]
  );

  const warehouseOptions = useMemo(
    () =>
      rawWarehouses.map((w) => ({
        value: String(w.id ?? w.value),
        label: w.name || w.warehouse_name || w.label || `Warehouse #${w.id}`,
      })),
    [rawWarehouses]
  );

  const productOptions = useMemo(
    () =>
      rawProducts.map((p) => {
        const name = p.name || p.product_name || p.label || `Product #${p.id}`;
        const code = p.code || p.sku;
        return {
          value: String(p.id ?? p.value),
          label: code ? `${name} (${code})` : name,
        };
      }),
    [rawProducts]
  );

  // ---- Edit mode: load the purchase order and prefill ----

  useEffect(() => {
    if (!isEdit) return;
    let active = true;

    (async () => {
      try {
        const po = await dispatch(getPurchaseOrderById(id)).unwrap();
        if (!active) return;

        setForm({
          vendorId: String(po.vendor?.id ?? po.vendor ?? ""),
          poNumber: po.po_number || "",
          prReference: po.pr_reference || "",
          orderDate: po.order_date || "",
          expectedDate: po.expected_delivery_date || "",
          paymentTerm: po.payment_terms || "",
          orderStatus: po.status || "draft",
          warehouse: String(po.warehouse?.id ?? po.warehouse ?? ""),
          shippingMethod: po.shipping_method || "",
          discount: numStr(po.discount),
          roundOff: numStr(po.round_off),
          notes: po.notes || "",
        });

        const loaded = (po.item_details || []).map((it, idx) => ({
          ...newItem(idx + 1),
          product: String(it.product?.id ?? it.product ?? ""),
          description: it.description || "",
          qty: numStr(it.quantity),
          hsCode: it.hs_code || "",
          rate: numStr(it.rate),
          vat: it.vat_percentage != null ? numStr(it.vat_percentage) : String(VAT_RATE),
        }));
        setItems(loaded.length ? loaded : [newItem(1)]);
      } catch (err) {
        setSaveError(formatError(err) || "Failed to load purchase order.");
      } finally {
        if (active) setIsLoading(false);
      }
    })();

    return () => {
      active = false;
    };
  }, [dispatch, id, isEdit]);

  // ---- Form fields ----

  const setField = (name, value) => {
    setForm((prev) => ({ ...prev, [name]: value }));
    setErrors((prev) => ({ ...prev, [name]: undefined }));
  };

  // Picking a vendor pre-fills its payment term when the dropdown row has one
  // that matches an available option (e.g. "30_days" -> "30 days")
  const handleVendorChange = (e) => {
    const vid = e.target.value;
    const vendor = sourceVendors.find((v) => String(v.id ?? v.value) === String(vid));
    const raw = vendor?.payment_terms || vendor?.payment_term;
    const normalized = raw ? String(raw).replace(/_/g, " ").toLowerCase() : "";
    const match = PAYMENT_TERMS.find((o) => o.value.toLowerCase() === normalized);

    setForm((prev) => ({
      ...prev,
      vendorId: vid,
      paymentTerm: match ? match.value : prev.paymentTerm,
    }));
    setErrors((prev) => ({ ...prev, vendorId: undefined }));
  };

  // ---- Items ----

  const addItem = () => setItems((prev) => [...prev, newItem(prev.length + 1)]);

  const removeItem = (itemId) =>
    setItems((prev) =>
      prev.length === 1
        ? prev // always keep one row
        : prev
            .filter((i) => i.id !== itemId)
            .map((i, idx) => ({ ...i, slNo: idx + 1 }))
    );

  const updateItem = (itemId, field, value) =>
    setItems((prev) => prev.map((i) => (i.id === itemId ? { ...i, [field]: value } : i)));

  // Picking a product fills description and HS code when the dropdown row has
  // them and the fields are still empty
  const selectProduct = (itemId, productId) => {
    const p = rawProducts.find((x) => String(x.id ?? x.value) === String(productId));

    setItems((prev) =>
      prev.map((i) =>
        i.id === itemId
          ? {
              ...i,
              product: productId,
              description: i.description || p?.description || "",
              hsCode: i.hsCode || p?.hs_code || "",
            }
          : i
      )
    );
  };

  // Rows with computed VAT and amount for display
  const rows = useMemo(
    () =>
      items.map((i) => {
        const t = rowTotals(i);
        return { ...i, vatAmount: fmt(t.vatAmount), amount: fmt(t.amount) };
      }),
    [items]
  );

  // Numbers used for both the summary and the payload
  const calc = useMemo(() => {
    const totals = items.map(rowTotals);
    const subTotal = totals.reduce((s, t) => s + t.base, 0);
    const vat = totals.reduce((s, t) => s + t.vatAmount, 0);
    const discount = toNum(form.discount);
    const roundOff = toNum(form.roundOff);
    // Assumes the backend does: total = subtotal + VAT - discount + round_off
    return { subTotal, vat, discount, roundOff, total: subTotal + vat - discount + roundOff };
  }, [items, form.discount, form.roundOff]);

  const summary = {
    subTotal: fmt(calc.subTotal),
    vat: fmt(calc.vat),
    discount: fmt(calc.discount),
    roundOff: fmt(calc.roundOff),
    total: fmt(calc.total),
  };

  // ---- Validation + save ----

  const validate = () => {
    const e = {};
    if (!form.vendorId) e.vendorId = "Select a vendor";
    if (!form.orderDate) e.orderDate = "Order date is required";
    if (!form.expectedDate) e.expectedDate = "Expected delivery date is required";
    else if (form.orderDate && form.expectedDate < form.orderDate)
      e.expectedDate = "Must be on or after the order date";
    if (!form.paymentTerm) e.paymentTerm = "Select payment terms";
    if (!form.orderStatus) e.orderStatus = "Select a status";
    if (!form.warehouse) e.warehouse = "Select a warehouse";
    if (!form.shippingMethod) e.shippingMethod = "Select a shipping method";

    const itemErrors = {};
    items.forEach((i) => {
      const r = {};
      if (!i.product) r.product = "Required";
      if (!(toNum(i.qty) > 0)) r.qty = "Enter qty";
      if (!(toNum(i.rate) > 0)) r.rate = "Enter rate";
      if (Object.keys(r).length) itemErrors[i.id] = r;
    });
    if (Object.keys(itemErrors).length) e.items = itemErrors;

    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleSave = async () => {
    setSaveError("");
    if (!validate()) return;

    setIsSaving(true);
    try {
      // po_number is generated by the backend, so it is never sent
      const payload = {
        vendor: Number(form.vendorId),
        pr_reference: form.prReference.trim() || undefined,
        order_date: form.orderDate,
        expected_delivery_date: form.expectedDate,
        payment_terms: form.paymentTerm,
        status: form.orderStatus,
        warehouse: Number(form.warehouse),
        shipping_method: form.shippingMethod,
        discount: money(calc.discount),
        round_off: money(calc.roundOff),
        notes: form.notes || undefined,
        items: items.map((i) => ({
          product: Number(i.product),
          description: i.description.trim() || undefined,
          quantity: money(toNum(i.qty)),
          hs_code: i.hsCode.trim() || undefined,
          rate: money(toNum(i.rate)),
          vat_percentage: money(toNum(i.vat)),
        })),
      };

      if (isEdit) {
        await dispatch(editPurchaseOrder({ id, data: payload })).unwrap();
      } else {
        await dispatch(addPurchaseOrder(payload)).unwrap();
      }
      navigate(LIST_ROUTE);
    } catch (err) {
      // Stay on the page so the user can fix the problem
      setSaveError(formatError(err) || "Failed to save purchase order.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => navigate(LIST_ROUTE);

  return {
    form,
    errors,
    saveError,
    rows,
    summary,
    isSaving,
    isEdit,
    isLoading,

    vendorOptions,
    warehouseOptions,
    productOptions,

    setField,
    handleVendorChange,
    addItem,
    removeItem,
    updateItem,
    selectProduct,
    handleSave,
    handleCancel,
    navigate,
  };
};

export default useAddingPurchaseOrder;